version: "3"
services:
  web:
    container_name: web_server
    build: ./web_server
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - docker_net

  db:
    container_name: mysql_server
    build: ./db_server
    volumes:
      - ./db_server/db_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge